(feature) Order history
bitfinexcom/ufx-ui pull request #3
Opened 2021-04-14 16:44 UTC by JasonMHasperhoven

## Prerequisites
N/A

(If the PR requires any other PRs to be applied first, indicate it here, otherwise put "N/A")

## Task reference

## PR description

## Example app screenshot
N/A

(Add example app screenshot if applicable, otherwise put "N/A")

## Storybook screenshot
N/A

(Add storybook screenshot if applicable, otherwise put "N/A")

## Checklist
  - [ ] PR title has category name prefix, e.g. "\(fix\) {description}" (fix/feature/refactor/improvement/doc/test)
  - [ ] Added PR description
  - [ ] Relevant change in example app is verified, added example app screenshot
  - [ ] Storybook: stories, docs are updated/verified
  - [ ] Tests/snapshots are updated
  - [ ] Lint check passed
  - [ ] PR development is completed, the developer is satisfied with the code quality and behavior of the app

2021-04-15 07:04 UTC, bhoomij requested changes
please add example app screenshot for orderhistory so we can make sure its not broken with this new updates. 
could you please mark done for all the checklist points, for now we have to do it manually :sweat:  until we add complete ci process

2021-04-15 12:39 UTC, JasonMHasperhoven commented on src/components/OrderHistory/OrderHistory.js
> +  })),
Understood

2021-04-15 13:32 UTC, JasonMHasperhoven commented on src/components/ui/Table/_Table.scss
> +$ufx-table-even-row-background-color: white !default;
I wasn't aware of this, good suggestion

2021-04-15 15:48 UTC, JasonMHasperhoven commented on src/containers/OrderHistory/OrderHistory.constants.js
> +import { ORDER_HISTORY_COLUMNS } from '../../components'
Yes will do it in a separate PR, or revert to KEYS as it's no longer needed.

2021-04-15 17:01 UTC, bhoomij commented on src/containers/OrderHistory/OrderHistory.constants.js
> +import { ORDER_HISTORY_COLUMNS } from '../../components'
yes, good if we revert to KEYS in this PR, and then in separate PR update at all relevant places

2021-04-15 17:06 UTC, bhoomij commented on src/containers/OrderHistory/OrderHistory.container.js
> +export default withResponsive(memo(OrderHistoryContainer))
I think withResponsive is not needed now in container

2021-04-15 17:11 UTC, bhoomij commented on src/components/OrderHistory/stories/OrderHistory.stories.js
> +  ],
columns should be removed as we removed that prop ?

2021-04-15 17:16 UTC, bhoomij commented on src/components/OrderHistory/OrderHistory.Row.js
> +  const orderedColumns = getOrderedColumns(visibleColumns, customMapping)
should we memoize columns ?

2021-04-21 05:37 UTC, bhoomij reviewed
@JasonMHasperhoven , if this is ready now, could you please complete following so we can proceed to merge it ? Thanks!
- revert back ORDER_HISTORY_COLUMNS to ORDER_HISTORY_KEYS
- add example app screenshot
- mark remaining checklist points as done

2021-04-21 13:39 UTC, jeojoe approved these changes

2021-04-21 13:39 UTC, merged