(improvement): Checkbox added classname for tooltip
bitfinexcom/ufx-ui pull request #82
Opened 2021-07-01 12:04 UTC by dmytroshch

## Prerequisites
N/A

(If the PR requires any other PRs to be applied first, indicate it here, otherwise put "N/A")

## Task reference

## BREAKING CHANGES
N/A

(Explain here, any breaking changes that do not have backward compatibility with previous versions of ufx-ui or keep N/A
i.e. if you renamed some component prop. Someone who is using previous version, should work on these updates, before upating their `ufx-ui` dependency to this version)

## PR description
Showing helping message in customized tooltip window

## Example app screenshot
![Снимок экрана от 2021-07-01 15-03-53](https://user-images.githubusercontent.com/81973123/124121459-96297a80-da7d-11eb-9801-9e5534867522.png)

(Add example app screenshot if applicable, otherwise put "N/A")

## Storybook screenshot
N/A

(Add storybook screenshot if applicable, otherwise put "N/A")

## Checklist
  - [ ] PR title has category name prefix, e.g. "\(fix\) {description}" (fix/feature/refactor/improvement/doc/test)
  - [ ] Added PR description
  - [ ] Relevant change in example app is verified, added example app screenshot
  - [ ] Storybook: stories, docs are updated/verified
  - [ ] `Pull request verify workflow` passed
  - [ ] PR development is completed, the developer is satisfied with the code quality and behavior of the app

2021-07-01 13:24 UTC, Blaumaus approved these changes

2021-07-04 19:49 UTC, bhoomij requested changes

2021-07-04 19:49 UTC, bhoomij commented on packages/core/src/components/ui/Checkbox/Checkbox.js
> +    helpMessageClassname,
please rename to `helpMessageClassName` to match with naming convention used in project  `headerClassName/cellClassName`

2021-07-07 06:48 UTC, bhoomij approved these changes

2021-07-07 06:48 UTC, merged